import { useMemo, useState } from 'react';
import ContentRail from '../components/ContentRail';
import MediaCard from '../components/MediaCard';
import ReleaseCard from '../components/ReleaseCard';
import NewsCard from '../components/NewsCard';
import { validateExtraList } from '../lib/contentValidation';
import { isVisibleRelease, sortReleasesByNewest } from '../lib/releaseVisibility';
import { SEARCH_FILTERS, createSearchText } from '../lib/searchUtils';

function ContinueReadingModule({ item, onClear }) { const title = item.releaseTitle || 'Continue Reading'; return <section className="continue-module" aria-label="Continue reading"><div className="continue-module-art">{item.image ? <img src={item.image} alt={`${title} cover`} className="release-image" /> : <div className="visual-fallback">Continue Reading</div>}</div><div className="continue-module-content"><p className="release-date">Continue Reading</p>{item.seriesTitle ? <p className="release-eyebrow">{item.seriesTitle}</p> : null}<h2>{title}</h2>{item.issueNumber ? <p className="release-detail">Issue {item.issueNumber}</p> : null}{item.pageNumber && item.totalPages ? <p className="release-detail">Page {item.pageNumber} of {item.totalPages}</p> : null}<div className="continue-module-actions"><a className="primary-button" href={`/read/${item.releaseSlug}`}>Continue Reading</a><button type="button" className="text-button" onClick={onClear}>Clear</button></div></div></section>; }

function SearchModule({ series, releases, extras, soundtracksBySeries }) {
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState('all');
  const seriesBySlug = useMemo(() => new Map(series.map((item) => [item.slug, item])), [series]); const safeSoundtracksBySeries = soundtracksBySeries || new Map();
  const seriesItems = useMemo(() => series.map((item) => ({ id: `series:${item.slug || item.title}`, type: 'series', title: item.title, description: item.shortDescription || item.tagline || item.longDescription, href: item.slug ? `/series/${item.slug}` : null, image: item.thumbnailImage || item.heroImage || item.image, eyebrow: 'Series', context: item.genre || item.tone, searchable: createSearchText([item.title, item.logoText, item.tagline, item.shortDescription, item.longDescription, item.genre, item.tone]) })), [series]);
  const visibleReleases = useMemo(() => releases.filter((item) => isVisibleRelease(item)), [releases]);
  const releaseItems = useMemo(() => visibleReleases.map((item) => ({ id: `release:${item.id || item.title}`, type: 'releases', title: item.title, description: item.description, href: item.id ? `/releases/${item.id}` : null, image: item.coverImage || item.image, seriesTitle: seriesBySlug.get(item.seriesSlug)?.title, issueNumber: item.issueNumber, searchable: createSearchText([item.title, String(item.issueNumber ?? ''), item.description, item.seriesSlug, item.releaseDate]) })), [visibleReleases, seriesBySlug]);
  const extrasItems = useMemo(() => validateExtraList(extras).map((extra, idx) => ({ id: `extra:${extra.seriesSlug || idx}:${extra.title || idx}`, type: 'extras', title: extra.title, description: extra.description, href: extra.url || extra.href || null, image: extra.image, eyebrow: extra.type || extra.label || 'Extra', seriesTitle: seriesBySlug.get(extra.seriesSlug)?.title || extra.seriesSlug, searchable: createSearchText([extra.title, extra.type, extra.label, extra.description, extra.seriesSlug]) })), [extras, seriesBySlug]);
  const soundtrackItems = useMemo(() => series.flatMap((item) => (safeSoundtracksBySeries.get(item.slug) || []).map((track, idx) => ({ id: `soundtrack:${item.slug || idx}:${track.title || track.trackTitle || idx}`, type: 'soundtracks', title: track.title || track.trackTitle, description: track.description, href: track.url || track.href || null, image: track.image, eyebrow: 'Soundtrack', seriesTitle: item.title, searchable: createSearchText([track.title, track.trackTitle, track.artist, track.description, track.mood, item.slug]) }))), [series, safeSoundtracksBySeries]);
  const normalizedQuery = query.trim().toLowerCase(); const hasQuery = normalizedQuery.length > 0;
  const groupedResults = useMemo(() => { if (!hasQuery) return { series: [], releases: [], extras: [], soundtracks: [] }; const matcher = (item) => item.searchable.includes(normalizedQuery) && item.title; const filtered = { series: seriesItems.filter(matcher), releases: releaseItems.filter(matcher), extras: extrasItems.filter(matcher), soundtracks: soundtrackItems.filter(matcher) }; if (filter === 'all') return filtered; return { series: filter === 'series' ? filtered.series : [], releases: filter === 'releases' ? filtered.releases : [], extras: filter === 'extras' ? filtered.extras : [], soundtracks: filter === 'soundtracks' ? filtered.soundtracks : [] }; }, [extrasItems, filter, hasQuery, normalizedQuery, releaseItems, seriesItems, soundtrackItems]);
  const hasResults = Object.values(groupedResults).some((items) => items.length > 0);
  return <section className="search-module" aria-label="Search content"><label className="search-field" htmlFor="home-search-input"><span>Search the archive</span><input id="home-search-input" type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search series, releases, extras, and soundtracks." /></label><div className="search-filters" role="tablist" aria-label="Content type filter">{SEARCH_FILTERS.map((value) => <button key={value} type="button" className={`search-filter ${filter === value ? 'is-active' : ''}`} onClick={() => setFilter(value)} aria-pressed={filter === value}>{value[0].toUpperCase() + value.slice(1)}</button>)}</div>{!hasQuery ? <p className="search-hint">Search series, releases, extras, and soundtracks.</p> : null}{hasQuery && !hasResults ? <p className="search-hint">No matching content found.</p> : null}{hasQuery && hasResults ? <div className="search-results">{groupedResults.series.length > 0 ? <ContentRail title="Series" emptyMessage=""><ul className="rail-row">{groupedResults.series.map((item) => <MediaCard key={item.id} className="series-card" href={item.href || undefined} image={item.image} title={item.title} description={item.description} eyebrow={item.eyebrow} subtitle={item.context} fallbackText={item.title} />)}</ul></ContentRail> : null}{groupedResults.releases.length > 0 ? <ContentRail title="Releases" emptyMessage=""><ul className="rail-row">{groupedResults.releases.map((item) => <ReleaseCard key={item.id} release={{ title: item.title, description: item.description, issueNumber: item.issueNumber, releaseDate: null, coverImage: item.image }} seriesTitle={item.seriesTitle} href={item.href || undefined} showDate={false} />)}</ul></ContentRail> : null}{groupedResults.extras.length > 0 ? <ContentRail title="Extras" emptyMessage=""><ul className="rail-row">{groupedResults.extras.map((item) => <MediaCard key={item.id} href={item.href || undefined} image={item.image} eyebrow={item.eyebrow} title={item.title} subtitle={item.seriesTitle} description={item.description} fallbackText={item.title} />)}</ul></ContentRail> : null}{groupedResults.soundtracks.length > 0 ? <ContentRail title="Soundtracks" emptyMessage=""><ul className="rail-row">{groupedResults.soundtracks.map((item) => <MediaCard key={item.id} href={item.href || undefined} image={item.image} eyebrow={item.eyebrow} title={item.title} subtitle={item.seriesTitle} description={item.description} fallbackText={item.title} />)}</ul></ContentRail> : null}</div> : null}</section>;
}

export default function HomePage({ series, releases, extras, soundtracksBySeries, continueReading, onClearContinueReading, news }) {
  const seriesBySlug = useMemo(() => new Map(series.map((item) => [item.slug, item])), [series]);
  const visibleReleases = useMemo(() => releases.map((item, index) => ({ item, index })).filter(({ item }) => isVisibleRelease(item)).sort((a, b) => sortReleasesByNewest(a.item, b.item, a.index, b.index)).map(({ item }) => item), [releases]);
  return <main className="page page-home"><header className="home-header"><h1>Star Splitter Visions</h1><p>Browse new releases and cinematic worlds across the Star Splitter slate.</p></header>{continueReading ? <ContinueReadingModule item={continueReading} onClear={onClearContinueReading} /> : null}<SearchModule series={series} releases={releases} extras={extras} soundtracksBySeries={soundtracksBySeries} /><ContentRail title="Latest Releases" emptyMessage="No releases available yet."><ul className="rail-row">{visibleReleases.map((release) => <ReleaseCard key={release.id} release={release} seriesTitle={seriesBySlug.get(release.seriesSlug)?.title || release.seriesSlug} />)}</ul></ContentRail><ContentRail title="Latest Updates" emptyMessage="No updates yet.">{news.length === 0 ? null : <ul className="news-grid news-grid-compact">{news.slice(0, 3).map((item) => <NewsCard key={item.slug} item={item} href={`/news/${item.slug}`} />)}</ul>}<a href="/news" className="primary-button">View All Updates</a></ContentRail><ContentRail title="Series" emptyMessage="No series available yet."><ul className="rail-row">{series.map((item) => <MediaCard key={item.slug} className="series-card" href={item.slug ? `/series/${item.slug}` : undefined} image={item.thumbnailImage || item.heroImage || item.image} alt={`${item.title} series art`} title={item.title} description={item.tagline || item.shortDescription || item.longDescription} fallbackText={item.logoText || item.title} />)}</ul></ContentRail></main>;
}
